source 'https://github.com/CocoaPods/Specs.git'

# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

# 对于我们使用cocoapod引入的第三方,我们可以在podfile文件中 增加一句  inhibit_all_warnings! 来要pod的工程不显示任何警告
inhibit_all_warnings!

target 'Example' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    use_frameworks!
    
    pod 'YJHomeKit', :path=> '../'
    
    # 提示组件框架
    pod 'SVProgressHUD'
    pod 'MBProgressHUD'
    
    # 自动布局
    pod 'Masonry'
    pod 'PureLayout'
    
    # AOP面向切面
#    pod 'Aspects'

    # 响应函数式框架
    pod 'ReactiveObjC'
    
    # 路由组件化解耦
#    pod 'JLRoutes'

    # 网络请求框架
    pod 'YTKNetwork'
    
    pod 'AFNetworking'
    
    # 打印 SDK
    #pod 'CocoaLumberjack'
    

#    pod 'React', :path => '../ReactNative/node_modules/react-native', :subspecs => [
#    'Core',
#    'DevSupport', # 如果RN版本 >= 0.43，则需要加入此行才能开启开发者菜单
#    'RCTText',
#    'RCTNetwork',
#    'RCTWebSocket', # 调试功能需要此模块
#    'RCTAnimation', # FlatList和原生动画功能需要此模块
#    ]
#    pod 'yoga', :path => '../ReactNative/node_modules/react-native/ReactCommon/yoga'
    
end
